In [3]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd

In [11]:
fcl = nn.Linear(3, 2)
x = torch.rand(1, 3)
print("Input:")
print("    ", x)


print("w and b:")
for param in fcl.parameters():
    print(param)

y = fcl(x)
print("Output:")
print("    ", y)

Input:
     tensor([[0.2450, 0.4613, 0.4595]])
w and b:
Parameter containing:
tensor([[-0.4793, -0.3357,  0.4047],
        [-0.1371,  0.2135, -0.5550]], requires_grad=True)
Parameter containing:
tensor([0.4234, 0.4845], requires_grad=True)
Output:
     tensor([[0.3370, 0.2944]], grad_fn=<AddmmBackward0>)


In [12]:
torch.rand(100, 6)

tensor([[0.0645, 0.0329, 0.6339, 0.4603, 0.7248, 0.8665],
        [0.3888, 0.9463, 0.4152, 0.2429, 0.1312, 0.7601],
        [0.1592, 0.8888, 0.1597, 0.3894, 0.1820, 0.4091],
        [0.2805, 0.7917, 0.1167, 0.8201, 0.7276, 0.9725]])

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device


device(type='cuda')